import React from 'react';
import type { LucideProps } from 'lucide-react-native';
import {
  Activity,
  AlarmClock,
  ArrowUp,
  Award,
  BatteryCharging,
  Bed,
  Bike,
  Brain,
  Calendar,
  CalendarCheck,
  ChartLine,
  ChartNoAxesColumn,
  Check,
  CircleAlert,
  CircleCheck,
  CirclePlus,
  ChevronLeft,
  ChevronRight,
  Clock,
  Cookie,
  Droplet,
  Dumbbell,
  EllipsisVertical,
  FileText,
  Flame,
  Flower2,
  Footprints,
  GitCompareArrows,
  GlassWater,
  Gauge,
  Hammer,
  Heart,
  HeartPulse,
  House,
  Info,
  Lightbulb,
  Lock,
  LogOut,
  MapPin,
  Minus,
  Moon,
  Move,
  Pencil,
  Plus,
  Reply,
  Route,
  Scale,
  Search,
  ShieldCheck,
  Sparkles,
  Sun,
  Sunrise,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Timer,
  TrendingDown,
  TrendingUp,
  Trophy,
  User,
  UserPlus,
  Utensils,
  Watch,
  Waves,
  Wheat,
  Wind,
  X,
  Zap,
} from 'lucide-react-native';
import { text } from '@/theme';

/** Registry of every Lucide icon the app uses, keyed by the prototype's names. */
const REGISTRY = {
  activity: Activity,
  'alarm-clock': AlarmClock,
  'arrow-up': ArrowUp,
  award: Award,
  'battery-charging': BatteryCharging,
  bed: Bed,
  bike: Bike,
  brain: Brain,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  'chart-line': ChartLine,
  'chart-no-axes-column': ChartNoAxesColumn,
  check: Check,
  'alert-circle': CircleAlert,
  'check-circle-2': CircleCheck,
  'plus-circle': CirclePlus,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  clock: Clock,
  cookie: Cookie,
  droplet: Droplet,
  dumbbell: Dumbbell,
  'ellipsis-vertical': EllipsisVertical,
  'file-text': FileText,
  flame: Flame,
  'flower-2': Flower2,
  footprints: Footprints,
  'git-compare-arrows': GitCompareArrows,
  'glass-water': GlassWater,
  gauge: Gauge,
  hammer: Hammer,
  heart: Heart,
  'heart-pulse': HeartPulse,
  house: House,
  info: Info,
  lightbulb: Lightbulb,
  lock: Lock,
  'log-out': LogOut,
  'map-pin': MapPin,
  minus: Minus,
  moon: Moon,
  move: Move,
  pencil: Pencil,
  plus: Plus,
  reply: Reply,
  route: Route,
  scale: Scale,
  search: Search,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  sun: Sun,
  sunrise: Sunrise,
  thermometer: Thermometer,
  'thumbs-down': ThumbsDown,
  'thumbs-up': ThumbsUp,
  timer: Timer,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  trophy: Trophy,
  user: User,
  'user-plus': UserPlus,
  utensils: Utensils,
  watch: Watch,
  waves: Waves,
  wheat: Wheat,
  wind: Wind,
  x: X,
  zap: Zap,
} as const;

export type IconName = keyof typeof REGISTRY;

export interface IconProps extends Omit<LucideProps, 'name'> {
  name: IconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

/**
 * Lucide icon, rounded ~2px stroke, colored by metric hue. The product's single
 * icon system — no emoji anywhere.
 */
export function Icon({ name, size = 20, color = text.primary, strokeWidth = 2, ...rest }: IconProps) {
  const LucideIcon = REGISTRY[name];
  if (!LucideIcon) return null;
  return <LucideIcon size={size} color={color} strokeWidth={strokeWidth} {...rest} />;
}
